keys:
  # users
  - &haru02w age1gzcypdx3vp2nd9zv8u8n444rxutwewtveu27yta6vzkkt2kjqd6sywev69
  # hosts
  - &testvm age1xd7uw00xddzmqcymfmfz4dp2fldk62hzadq3f28mnvk3q2d46qqsp5jjc8
  - &zephyrus age1zzh8860ya7ghaz4xrqntwfj7ahnh6p82e6jdvuqewlnaehe6ve3qnzudu5
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *haru02w
        - *testvm
        - *zephyrus
