keys:
  - &backup age1gzcypdx3vp2nd9zv8u8n444rxutwewtveu27yta6vzkkt2kjqd6sywev69
  # hosts
  - &testvm age19jkafypluemrs3jqttzdt04rjp597u3q05yua7zaegqjnyznssnqn0rcpl
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *backup
        - *testvm
