on:
  pull_request:
  push:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  flake-check:
    name: Nix flake check
    runs-on: ubuntu-latest
    steps:
      - uses: wimpysworld/nothing-but-nix@main
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: actions/checkout@v5
      - run: nix flake metadata
      - run: |
          cat <<-EOF > modules/ci-runtime.nix
          {
            _module.args.CI = true;
          }
          EOF
      - run: nix flake check -L
